name: Terraform Deploy

on:
  workflow_dispatch:

jobs:
  terraform-dev:
    runs-on: label-1
    env:
      AWS_DEFAULT_REGION: ap-south-1   # must match your backend region

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan  -var-file=dev.tfvars
      - name: Terraform Apply Dev
        run: terraform apply -var-file=dev.tfvars -auto-approve

  terraform-prod:
    runs-on: label-1
    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan  -var-file=prod.tfvars
      - name: Terraform Apply Prod
        run: terraform apply -var-file=prod.tfvars -auto-approve
