name: Terraform EC2 Destroy

on:
  workflow_dispatch:   # allows manual trigger from Actions tab

jobs:
  terraform:
    runs-on: label-1
    env:
      
      AWS_DEFAULT_REGION: ap-south-1   # must match your backend region

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform Init
        run: terraform init
       

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars -var-file=prod.tfvars
        

      - name: Terraform Destroy
        run: terraform destroy -var-file=dev.tfvars -var-file=prod.tfvars -auto-approve
